###
GET http://localhost:3000/carros
Content-Type: application/json
Accept: application/json

###

POST http://localhost:3000/carros
Content-Type: application/json
Accept: application/json

{
    "marca_id": 1, 
    "modelo": "Série 3",
    "ano": 2024,
    "mes": 5,
    "cor": "Preto",
    "combustivel": "Gasolina",
    "fotos": [
        { "url": "https://www.bmw.pt/content/dam/bmw/common/all-models/m-series/m8-coupe/2022/navigation/bmw-8series-coupe-modellfinder.png"}
    ]
}

###
PUT http://localhost:3000/carros/1
Content-Type: application/json
Accept: application/json

{
    "marca_id": 1, 
    "modelo": "Série 7",
    "ano": 2021,
    "mes": 5,
    "cor": "Preto",
    "combustivel": "Gasolina",
    "fotos": [
        { "url": "https://www.bmw.pt/content/dam/bmw/common/all-models/m-series/m8-coupe/2022/navigation/bmw-8series-coupe-modellfinder.png"}
    ]
}

###
GET http://localhost:3000/carros/1
Content-Type: application/json
Accept: application/json


###
DELETE  http://localhost:3000/carros/2
Content-Type: application/json
Accept: application/json
