###
GET http://localhost:3000/signup
Content-Type: application/json
Accept: application/json


###
POST http://localhost:3000/clientes
Content-Type: application/json
Accept: application/json

{
    "nome": "john doe",
    "nif": "1235677",
    "email": "email@gmail.com",
    "password": "blabla"
}


###
PUT http://localhost:3000/clientes/1
Content-Type: application/json
Accept: application/json

{
    "nome": "john doe22",
    "nif": "12356",
    "email": "email@gmail.com",
    "password": "blabla"
}

###
GET http://localhost:3000/clientes/1
Content-Type: application/json
Accept: application/json


###
DELETE  http://localhost:3000/clientes/2
Content-Type: application/json
Accept: application/json
