###
GET http://localhost:3000/marcas
Content-Type: application/json
Accept: application/json

###
POST http://localhost:3000/marcas
Content-Type: application/json
Accept: application/json

{
    "nome": "bmw"
}


###
PUT http://localhost:3000/marcas/1
Content-Type: application/json
Accept: application/json

{
    "nome": "ford"
}

###
GET http://localhost:3000/marcas/1
Content-Type: application/json
Accept: application/json


###
DELETE  http://localhost:3000/marcas/2
Content-Type: application/json
Accept: application/json
